// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddressAutocompleteController from "./address_autocomplete_controller"
application.register("address-autocomplete", AddressAutocompleteController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import LikeController from "./like_controller"
application.register("like", LikeController)

import MapController from "./map_controller"
application.register("map", MapController)

import PicturesActivitiesController from "./pictures_activities_controller"
application.register("pictures-activities", PicturesActivitiesController)

import InsertInListController from "./insert_in_list_controller"
application.register("insert-in-list", InsertInListController)

import RelationshipController from "./relationship_controller"
application.register("relationship", RelationshipController)
